# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.18"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.18/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "d7c4f00a9731b6f5aef5f8974c09344425459c13667b51c7a06a2ccaf094f111"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.18/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "cdf2c93d6f95553a2d45c78157b8fede9a9d197a769dc55142c8c8afd3b73bad"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.18/cloudcrafter-linux-amd64.tar.gz"
        sha256 "00cff45e9e8740f709493b85458243bbbd2870d4c94835c2fd2ce39aabdca871"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.18/cloudcrafter-linux-arm64.tar.gz"
        sha256 "c327cb70822b492f93873491ec1867e55e499cce871a013d7cabe6aa491def11"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
