# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.17/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "2543497586180a25aa52b5294f4921ef14d75ffd3f38842dee9229a760e032a0"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.17/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "c1e8f12ce9b583c7928d542698e1220399597ac46061d5a0b7b5d08655e8ec4b"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.17/cloudcrafter-linux-amd64.tar.gz"
        sha256 "cc5123ad2f82d992a9203e166507b77b61f73560850915aa58295936867d25fd"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.17/cloudcrafter-linux-arm64.tar.gz"
        sha256 "cb022d03813b4dc76c07f5da5972516d67eca536ef6527c40ea336ea3e2622d4"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
