# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.16"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.16/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "eaf98d8b12e745db9e99d2c031e1ca564eaa6c8eab71ce01ce0b41ba3b224dc6"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.16/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "daea88cbda8f623fe6b31cf6a51b5f5897a73c121fc94c9d07b8c5a2eee58b6f"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.16/cloudcrafter-linux-amd64.tar.gz"
        sha256 "23c6218a1df3956bd2d6e138771b41d6642479c25b98f557835302788f02249e"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.16/cloudcrafter-linux-arm64.tar.gz"
        sha256 "71344d53f98c9872fca7f15a34945cdf4b30cffb95e52712c273c44de482b71d"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
