# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.21"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.21/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "fda8cf6868103e9f7ff299914d180c3ea08ecb0e1e5e181d155cf5c326f6a941"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.21/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "0917362a4fde6c29bc319dccf79e790ad7c573fdceb2b894fc160f161a3a2709"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.21/cloudcrafter-linux-amd64.tar.gz"
        sha256 "0370b384944ed576a6f3b9eb212376c0882ccb21cd7244c8350768671770a116"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.21/cloudcrafter-linux-arm64.tar.gz"
        sha256 "24d9667a399f0daab46b79a5d4f9b80b311ad503adab1bcf501e370261ac7c99"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
