# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.22/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "c140bebbff2b413737000477b7f2d2f60694a30f08c8e581e5cb8c6ca5e3b81f"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.22/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "bbf7c30919862cf173755714240e6362907d95634a3753eb722850274710fd4f"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.22/cloudcrafter-linux-amd64.tar.gz"
        sha256 "31a4767e69462e27a124522207f8ab52be3017801faba9d923177d02729e8619"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.22/cloudcrafter-linux-arm64.tar.gz"
        sha256 "40d34941c705a41c8e5c27c8dcbc684bb9338b2d214870b2203e146342220d4a"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
