# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudcrafter < Formula
  desc "CLI for multi-cloud provisioning and resource management"
  homepage "https://github.com/Omotolani98/cloudcrafter"
  version "1.0.19"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.19/cloudcrafter-darwin-amd64.tar.gz"
      sha256 "ccb2e798468875c0309bdb491d1894583e048679ae752a615097b5831a09ca90"

      def install
        bin.install "cloudcrafter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.19/cloudcrafter-darwin-arm64.tar.gz"
      sha256 "ba808045e3a9725349ac44e090434d64ff2533d26ea67896209e7c4066b6c848"

      def install
        bin.install "cloudcrafter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.19/cloudcrafter-linux-amd64.tar.gz"
        sha256 "ea01eb03658f342df85ca80a61175108fdb740ae74331bfcb675904e53bfe28f"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Omotolani98/cloudcrafter/releases/download/v1.0.19/cloudcrafter-linux-arm64.tar.gz"
        sha256 "9cccb4fc66af05e435c161b28413489cb1b20b1d773676c3a8f7a43ac7f3196f"

        def install
          bin.install "cloudcrafter"
        end
      end
    end
  end

  def caveats
    <<~EOS
      To use CloudCrafter CLI, add it to your PATH.
      Example: export PATH="$PATH:/usr/local/bin/cloudcrafter"
    EOS
  end

  test do
    system "#{bin}/cloudcrafter --version"
  end
end
